version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      APP_KEY: base64:Rf1aqxxb9e23SsIKhBcgrQM7Y2/pyKQJFxcT+tfk97o=
      DB_CONNECTION: mysql
      DB_HOST: laravel.cvkw8si2mrzq.us-east-1.rds.amazonaws.com
      DB_PORT: 3306
      DB_DATABASE: l_12_local
      DB_USERNAME: admin
      DB_PASSWORD: admin123
    volumes:
      - storage:/var/www/html/storage:rw
      - public:/var/www/html/public:rw

volumes:
  storage:
  public:
