version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - storage:/var/www/html/storage:rw
      - public:/var/www/html/public:rw

volumes:
  storage:
  public:
